name: Build
on:
  push:
    branches:
      - main
jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4 
      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .
  unit-test:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install packages
        run: pip install -r requirements.txt && pip install pytest
      - name: Run unit tests using pytest
        run: pytest
        env:
            DB_URL: ${{ secrets.DB_URL }}
            DB_KEY: ${{ secrets.DB_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
  build-push-deploy-image:
    needs: [python-formatting, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
      - name: ImPaaS-Deploy
        id: impaas-deploy
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: gyya-sse2-users-service
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: DOCKER_IMAGE
